"""
data_ingestion.py
-----------------
Loads all 10 raw CSVs from data/raw/, prints shape / dtypes / head / null counts,
and writes a data_quality_report.md to the project root.
"""

import pandas as pd
from pathlib import Path

RAW = Path("data/raw")
REPORT_PATH = Path("data_quality_report.md")

CSV_FILES = [
    "fund_master.csv",
    "nav_history.csv",
    "aum_history.csv",
    "investor_transactions.csv",
    "sip_register.csv",
    "scheme_performance.csv",
    "portfolio_holdings.csv",
    "benchmark_returns.csv",
    "investor_demographics.csv",
    "distributor_data.csv",
]


def load_all(raw_dir: Path) -> dict[str, pd.DataFrame]:
    """Load every CSV in CSV_FILES from raw_dir and return as a dict."""
    dfs = {}
    for fname in CSV_FILES:
        path = raw_dir / fname
        if not path.exists():
            print(f"  [WARN] {fname} not found – skipping")
            continue
        dfs[fname] = pd.read_csv(path)
        print(f"  ✔ Loaded {fname:45s}  shape={dfs[fname].shape}")
    return dfs


def build_quality_report(dfs: dict[str, pd.DataFrame]) -> str:
    """Return a markdown string summarising data quality for each dataframe."""
    lines = [
        "# Bluestock MF – Data Quality Report",
        "",
        "> Auto-generated by `scripts/data_ingestion.py`",
        "",
    ]

    anomalies_found = []

    for fname, df in dfs.items():
        lines += [
            f"---",
            f"## {fname}",
            f"",
            f"**Shape**: {df.shape[0]:,} rows × {df.shape[1]} columns",
            f"",
            "**Column dtypes:**",
            "",
            "| Column | dtype |",
            "|--------|-------|",
        ]
        for col, dtype in df.dtypes.items():
            lines.append(f"| `{col}` | `{dtype}` |")

        # null analysis
        null_counts = df.isnull().sum()
        null_cols   = null_counts[null_counts > 0]
        lines += ["", "**Missing values:**", ""]
        if null_cols.empty:
            lines.append("_No missing values detected._")
        else:
            lines += ["| Column | Null Count | Null % |", "|--------|-----------|--------|"]
            for col, cnt in null_cols.items():
                pct = round(cnt / len(df) * 100, 2)
                lines.append(f"| `{col}` | {cnt} | {pct}% |")
                anomalies_found.append(f"{fname}::{col} — {cnt} nulls ({pct}%)")

        # numeric anomalies
        lines += ["", "**Numeric summary (first 5 numeric cols):**", ""]
        num_cols = df.select_dtypes(include="number").columns[:5]
        if len(num_cols):
            desc = df[num_cols].describe().round(4)
            header = "| stat | " + " | ".join(desc.columns) + " |"
            sep    = "|------|" + "|".join(["------"] * len(desc.columns)) + "|"
            lines += [header, sep]
            for idx, row in desc.iterrows():
                lines.append("| " + str(idx) + " | " + " | ".join(str(v) for v in row.values) + " |")

        # duplicate rows
        dup_count = df.duplicated().sum()
        lines += ["", f"**Duplicate rows**: {dup_count}", ""]

        # specific checks
        if "nav" in df.columns:
            neg_nav = (df["nav"] < 0).sum()
            if neg_nav:
                anomalies_found.append(f"{fname}::nav — {neg_nav} negative values")
                lines.append(f"> ⚠️  {neg_nav} negative NAV values detected.")

        if "expense_ratio" in df.columns:
            high_er = (df["expense_ratio"] > 3.0).sum()
            if high_er:
                anomalies_found.append(f"{fname}::expense_ratio — {high_er} values > 3% (SEBI limit breach)")
                lines.append(f"> ⚠️  {high_er} expense_ratio values > 3% — likely data errors.")

        if "amount" in df.columns:
            neg_amt = (df["amount"] < 0).sum()
            if neg_amt:
                anomalies_found.append(f"{fname}::amount — {neg_amt} negative amounts")

        if "kyc_status" in df.columns:
            rej = (df["kyc_status"] == "Rejected").sum()
            if rej:
                anomalies_found.append(f"{fname}::kyc_status — {rej} Rejected KYC records")
                lines.append(f"> ⚠️  {rej} transactions from investors with Rejected KYC.")

        lines.append("")

    # summary section
    lines += [
        "---",
        "## Summary of Anomalies",
        "",
        "| # | Issue |",
        "|---|-------|",
    ]
    for i, anomaly in enumerate(anomalies_found, 1):
        lines.append(f"| {i} | {anomaly} |")

    if not anomalies_found:
        lines.append("_No anomalies detected._")

    lines += [
        "",
        "---",
        "## Next Step",
        "",
        "Run `scripts/clean_data.py` to apply forward-fill, deduplication, "
        "KYC filtering, and expense-ratio capping.",
    ]

    return "\n".join(lines)


if __name__ == "__main__":
    print("=" * 60)
    print("  Bluestock MF – Data Ingestion")
    print("=" * 60)

    dfs = load_all(RAW)

    print("\n--- Null Counts per File ---")
    for fname, df in dfs.items():
        nulls = df.isnull().sum().sum()
        print(f"  {fname:45s}  total_nulls={nulls}")

    report_md = build_quality_report(dfs)
    REPORT_PATH.write_text(report_md, encoding="utf-8")
    print(f"\n✅ Data quality report written to {REPORT_PATH}")

    # assertions
    assert len(dfs) == len(CSV_FILES), "Some CSV files failed to load!"
    for fname, df in dfs.items():
        assert len(df) > 0, f"{fname} is empty!"
    print("✅ All assertions passed.")
