"""
data_ingestion.py
-----------------
Loads all 10 real CSVs from data/raw/, validates shapes/dtypes/nulls,
and writes data_quality_report.md.
Real dataset: SBI, HDFC, ICICI, Nippon, Kotak, Axis, ABSL, UTI, Mirae, DSP funds.
"""

import pandas as pd
from pathlib import Path

RAW = Path("data/raw")
REPORT_PATH = Path("data_quality_report.md")

CSV_FILES = [
    "01_fund_master.csv",
    "02_nav_history.csv",
    "03_aum_by_fund_house.csv",
    "04_monthly_sip_inflows.csv",
    "05_category_inflows.csv",
    "06_industry_folio_count.csv",
    "07_scheme_performance.csv",
    "08_investor_transactions.csv",
    "09_portfolio_holdings.csv",
    "10_benchmark_indices.csv",
]


def load_all(raw_dir: Path) -> dict:
    dfs = {}
    for fname in CSV_FILES:
        path = raw_dir / fname
        if not path.exists():
            print(f"  [WARN] {fname} not found – skipping")
            continue
        dfs[fname] = pd.read_csv(path)
        print(f"  ✔ Loaded {fname:45s}  shape={dfs[fname].shape}")
    return dfs


def build_quality_report(dfs: dict) -> str:
    lines = [
        "# Bluestock MF – Data Quality Report (Real Dataset)",
        "",
        "> Auto-generated by `scripts/data_ingestion.py`",
        "> Dataset: Real AMFI/SEBI MF data — SBI, HDFC, ICICI Prudential, Nippon India, Kotak, Axis, ABSL, UTI, Mirae Asset, DSP",
        "",
    ]
    anomalies = []

    for fname, df in dfs.items():
        lines += [f"---", f"## {fname}", "",
                  f"**Shape**: {df.shape[0]:,} rows × {df.shape[1]} columns", ""]
        lines += ["**Columns:**", ""]
        for col, dtype in df.dtypes.items():
            lines.append(f"- `{col}` ({dtype})")

        null_counts = df.isnull().sum()
        null_cols   = null_counts[null_counts > 0]
        lines += ["", "**Missing values:**", ""]
        if null_cols.empty:
            lines.append("_No missing values._")
        else:
            lines += ["| Column | Nulls | % |", "|--------|-------|---|"]
            for col, cnt in null_cols.items():
                pct = round(cnt / len(df) * 100, 2)
                lines.append(f"| `{col}` | {cnt} | {pct}% |")
                anomalies.append(f"{fname}::{col} — {cnt} nulls ({pct}%)")

        dups = df.duplicated().sum()
        lines += ["", f"**Duplicate rows**: {dups}", ""]

        # specific checks
        if "nav" in df.columns:
            neg = (pd.to_numeric(df["nav"], errors="coerce") < 0).sum()
            if neg:
                anomalies.append(f"{fname}::nav — {neg} negative values")
                lines.append(f"> ⚠️ {neg} negative NAV values")

        if "expense_ratio_pct" in df.columns:
            high = (pd.to_numeric(df["expense_ratio_pct"], errors="coerce") > 3.0).sum()
            if high:
                anomalies.append(f"{fname}::expense_ratio_pct — {high} values > 3%")
                lines.append(f"> ⚠️ {high} expense_ratio_pct > 3%")

        if "return_1yr_pct" in df.columns:
            extreme = ((df["return_1yr_pct"] < -100) | (df["return_1yr_pct"] > 300)).sum()
            if extreme:
                anomalies.append(f"{fname}::return_1yr_pct — {extreme} extreme values")

        lines.append("")

    lines += ["---", "## Anomaly Summary", ""]
    for i, a in enumerate(anomalies, 1):
        lines.append(f"{i}. {a}")
    if not anomalies:
        lines.append("_No anomalies found._")

    return "\n".join(lines)


if __name__ == "__main__":
    print("=" * 60)
    print("  Bluestock MF – Data Ingestion (Real Dataset)")
    print("=" * 60)

    dfs = load_all(RAW)

    print("\n--- Null Counts ---")
    for fname, df in dfs.items():
        nulls = df.isnull().sum().sum()
        print(f"  {fname:45s}  nulls={nulls}")

    # Sample real fund names
    if "01_fund_master.csv" in dfs:
        fm = dfs["01_fund_master.csv"]
        print("\n--- Sample Fund Houses (real data) ---")
        print(fm[["fund_house","scheme_name","category"]].head(5).to_string(index=False))

    report = build_quality_report(dfs)
    REPORT_PATH.write_text(report, encoding="utf-8")
    print(f"\n✅ Quality report → {REPORT_PATH}")

    assert len(dfs) == len(CSV_FILES), "Missing CSV files"
    for fname, df in dfs.items():
        assert len(df) > 0, f"{fname} empty"
    print("✅ All assertions passed.")
